//! The command-and-event C ABI.
//!
//! The workspace owns no chess state. It creates a session, submits commands
//! describing player intent, and drains events describing the state to draw.
//! Payloads are UTF-8 JSON so their shape can grow without ABI changes.
//!
//! See `include/omachess_core.h` for the header the workspace compiles against.

use std::ffi::{c_char, CStr, CString};

use crate::session::{CommandError, Session};

/// An opaque handle to a workspace session.
pub struct OmachessSession {
    inner: Session,
}

pub const OMACHESS_OK: i32 = 0;
pub const OMACHESS_ERR_UNKNOWN_COMMAND: i32 = 1;
pub const OMACHESS_ERR_MALFORMED_COMMAND: i32 = 2;
pub const OMACHESS_ERR_NULL_ARGUMENT: i32 = 3;
pub const OMACHESS_ERR_INVALID_UTF8: i32 = 4;
pub const OMACHESS_ERR_REJECTED_MOVE: i32 = 5;

/// Creates a session holding the standard-chess starting position.
///
/// The caller owns the returned handle and must release it with
/// `omachess_session_free`.
#[no_mangle]
pub extern "C" fn omachess_session_new() -> *mut OmachessSession {
    Box::into_raw(Box::new(OmachessSession { inner: Session::new() }))
}

/// Releases a session. Passing null is a no-op.
///
/// # Safety
/// `session` must be a handle from `omachess_session_new` that has not already
/// been freed.
#[no_mangle]
pub unsafe extern "C" fn omachess_session_free(session: *mut OmachessSession) {
    if !session.is_null() {
        drop(Box::from_raw(session));
    }
}

/// Submits one command as a NUL-terminated UTF-8 JSON string.
///
/// Returns `OMACHESS_OK`, or an `OMACHESS_ERR_*` code when the command was
/// rejected. A rejected command changes no state and queues no events.
///
/// # Safety
/// `session` must be a live handle and `command_json` a valid NUL-terminated
/// string for the duration of the call.
#[no_mangle]
pub unsafe extern "C" fn omachess_session_submit(
    session: *mut OmachessSession,
    command_json: *const c_char,
) -> i32 {
    let (Some(session), false) = (session.as_mut(), command_json.is_null()) else {
        return OMACHESS_ERR_NULL_ARGUMENT;
    };
    let Ok(command) = CStr::from_ptr(command_json).to_str() else {
        return OMACHESS_ERR_INVALID_UTF8;
    };
    match session.inner.submit(command) {
        Ok(()) => OMACHESS_OK,
        Err(CommandError::UnknownCommand) => OMACHESS_ERR_UNKNOWN_COMMAND,
        Err(CommandError::MalformedCommand) => OMACHESS_ERR_MALFORMED_COMMAND,
        Err(CommandError::RejectedMove) => OMACHESS_ERR_REJECTED_MOVE,
    }
}

/// Removes the oldest queued event and returns it as UTF-8 JSON, or null when
/// the queue is empty.
///
/// The caller owns the returned string and must release it with
/// `omachess_string_free`.
///
/// # Safety
/// `session` must be a live handle.
#[no_mangle]
pub unsafe extern "C" fn omachess_session_poll_event(
    session: *mut OmachessSession,
) -> *mut c_char {
    let Some(session) = session.as_mut() else {
        return std::ptr::null_mut();
    };
    match session.inner.poll_event() {
        // Events are generated by this crate and never contain interior NULs.
        Some(event) => CString::new(event)
            .map(CString::into_raw)
            .unwrap_or(std::ptr::null_mut()),
        None => std::ptr::null_mut(),
    }
}

/// Releases a string returned by this ABI. Passing null is a no-op.
///
/// # Safety
/// `text` must come from `omachess_session_poll_event` and must not have been
/// freed already.
#[no_mangle]
pub unsafe extern "C" fn omachess_string_free(text: *mut c_char) {
    if !text.is_null() {
        drop(CString::from_raw(text));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    unsafe fn drain(session: *mut OmachessSession) -> Vec<String> {
        let mut events = Vec::new();
        loop {
            let event = omachess_session_poll_event(session);
            if event.is_null() {
                return events;
            }
            events.push(CStr::from_ptr(event).to_str().unwrap().to_owned());
            omachess_string_free(event);
        }
    }

    #[test]
    fn a_session_round_trips_a_command_into_an_event() {
        unsafe {
            let session = omachess_session_new();
            let command = CString::new(r#"{"type":"describe_board"}"#).unwrap();
            assert_eq!(omachess_session_submit(session, command.as_ptr()), OMACHESS_OK);
            let events = drain(session);
            assert_eq!(events.len(), 1);
            assert!(events[0].contains(r#""orientation":"white""#));
            omachess_session_free(session);
        }
    }

    #[test]
    fn rejected_commands_report_a_code_and_produce_no_events() {
        unsafe {
            let session = omachess_session_new();
            let command = CString::new(r#"{"type":"castle"}"#).unwrap();
            assert_eq!(
                omachess_session_submit(session, command.as_ptr()),
                OMACHESS_ERR_UNKNOWN_COMMAND
            );
            assert!(drain(session).is_empty());
            omachess_session_free(session);
        }
    }

    #[test]
    fn null_arguments_are_reported_rather_than_dereferenced() {
        unsafe {
            let command = CString::new(r#"{"type":"flip_board"}"#).unwrap();
            assert_eq!(
                omachess_session_submit(std::ptr::null_mut(), command.as_ptr()),
                OMACHESS_ERR_NULL_ARGUMENT
            );
            let session = omachess_session_new();
            assert_eq!(
                omachess_session_submit(session, std::ptr::null()),
                OMACHESS_ERR_NULL_ARGUMENT
            );
            omachess_session_free(session);
            omachess_session_free(std::ptr::null_mut());
            omachess_string_free(std::ptr::null_mut());
        }
    }
}
